export function getEmptyProjectStructure(id: number | string) {
  return {
    id: String(id),
    title: 'New Project',
    description: 'Brand new project',
    pages: {},
    url: '',
    content: {},
    colors: {
      bg_1: { c: '#f8fafc', key: 'bg_1' },
      text_1: { c: '#0f172a', key: 'text_1' },
      bg_2: { c: '#f1f5f9', key: 'bg_2' },
      text_2: { c: '#475569', key: 'text_2' },
      bg_3: { c: '#6366f1', key: 'bg_3' },
      text_3: { c: '#ffffff', key: 'text_3' },
      bg_4: { c: '#e0e7ff', key: 'bg_4' },
      text_4: { c: '#3730a3', key: 'text_4' },
      bg_5: { c: '#fef3c7', key: 'bg_5' },
      text_5: { c: '#92400e', key: 'text_5' },
      bg_1_dark: { c: '#0f172a', key: 'bg_1_dark' },
      text_1_dark: { c: '#f8fafc', key: 'text_1_dark' },
      bg_2_dark: { c: '#1e293b', key: 'bg_2_dark' },
      text_2_dark: { c: '#94a3b8', key: 'text_2_dark' },
      bg_3_dark: { c: '#4f46e5', key: 'bg_3_dark' },
      text_3_dark: { c: '#ffffff', key: 'text_3_dark' },
      bg_4_dark: { c: '#1e1b4b', key: 'bg_4_dark' },
      text_4_dark: { c: '#a5b4fc', key: 'text_4_dark' },
      bg_5_dark: { c: '#292524', key: 'bg_5_dark' },
      text_5_dark: { c: '#fcd34d', key: 'text_5_dark' },
    },
    users: {},
  }
}
